apiVersion: v1
kind: ReplicationController
metadata:
  name: es-client
  labels:
    component: elasticsearch
    role: client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: elasticsearch
        role: client
    spec:
      initContainers: 
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true      
      containers:
      - name: es-client
        securityContext:
          privileged: true 
          ## Fix for DNM, we only need this:
          # capabilities:
          #   add:
          #     - IPC_LOCK
          #     - SYS_RESOURCE
        image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
        command: ["bin/elasticsearch"]
        args: 
          [
          "-Ecluster.name=myesdb",
          "-Enode.master=false",
          "-Enode.data=false",
          "-Ehttp.enabled=true",
          "-Ediscovery.zen.ping.unicast.hosts=elasticsearch-discovery",
          "-Expack.security.enabled=false"
          ]
        env:
        - name: "ES_JAVA_OPTS"
          value: "-Xms1g -Xmx1g"
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 1Gi
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: storage
      volumes:
      - name: storage
        emptyDir: {}
